server:
  port: 8080
  context-path: /chishenme

spring:
  application:
    name: chishenme
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/chishenme?characterEncoding=utf-8
    username: root
    password: root